### ISSUE TITLE
Call far and Jump far to an invalid address freezes the UI

### ISSUE THREAD

**Issue by TheTompiler** [shooshx/corewars8086_js#19]
This problem has already been opened, but I wanted to generalize it and elaborate on the situation.
![image](https://user-images.githubusercontent.com/67478051/104882407-bbad4680-596b-11eb-918d-9d4f1088b0f7.png)
![image](https://user-images.githubusercontent.com/67478051/104882439-c49e1800-596b-11eb-9079-9b399479e8ed.png)

**Comment by shooshx** [comment]
fixed

**Comment by TheTompiler** [comment]
Thanks you very much! although, now when you try to execute call far to an invalid location it doesn't kill the survivor, but stops you from executing another step.
![image](https://user-images.githubusercontent.com/67478051/105024528-e0311d80-5a54-11eb-98c9-059c5fd49428.png)
![image](https://user-images.githubusercontent.com/67478051/105024552-e7582b80-5a54-11eb-95ee-fe3f8b76775d.png)
![image](https://user-images.githubusercontent.com/67478051/105024581-f048fd00-5a54-11eb-83e0-364c7ee8a3f9.png)

**Comment by shooshx** [comment]
What makes you think that it doesn't kill the survivor?
If you look at the messages box below you can even see in your screenshot that it says "Player_A died due to memory exception ..."
The reason that you don't see the blue highlight line is that the debugging window only shows addresses that are in the arena and cs:ip = cccc:cccc is outside the arena.

There is another bug I'm seeing now that if you stop the debug session and start again, it still doesn't show the blue highlight line. You can fix that by moving to another warrior and back (assuming you have more than 1). I'll fix that later today
